version: '3'

services:
  loei-a6-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-a6
    restart: unless-stopped
    volumes:
      - .:/app
      - ./docker/nginx:/etc/nginx/config.d
    ports:
      - '80:80'

networks:
  default:
    external:
      name: default-net
