<template>
  <div>
    <iframe
      style="width:100%;height:800px"
      src="https://pubhtml5.com/bookcase/bsrn/gold"
      seamless="seamless"
      scrolling="no"
      frameborder="0"
      allowtransparency="true"
      allowfullscreen
    ></iframe>
  </div>
</template>
